namespace ANIMALITOS_PHARMA_API.Accessors.Util.StatusEnumerable
{
    public enum ObjectStatus : int
    {
        INACTIVE = 0,
        ACTIVE = 1,
        PRODUCT_AVAILABLE = 100,
        PRODUCT_SOLD_OUT = 101,
        PRODUCT_DISCONTINUED = 102,
        PRODUCT_LOT_COMPLETE = 200,
        PRODUCT_LOT_INCOMPLETE = 201,
        PRODUCT_LOT_DAMAGED = 202,
        PRODUCT_LOT_EXPIRED = 203,
        INVENTORY_ITEM_STORE_AVAILABLE = 300,
        INVENTORY_ITEM_STORE_DAMAGED = 301,
        INVENTORY_ITEM_STORE_EXPIRED = 302,
        INVENTORY_ITEM_ON_ROUTE = 303,
        INVENTORY_ITEM_SOLD = 304,
        INVENTORY_ITEM_DAMAGED_ROUTE = 305,
        CREDIT_ACTIVE = 400,
        CREDIT_PAID = 401,
        CREDIT_EXPECTED = 402,
        CREDIT_PAID_DELAY = 403,
        UNIT_TEST_CREATE = 10000,
        UNIT_TEST_UPDATE = 10001
    }
}